version: '3'

services:
  shaarli:
    image: shaarli/shaarli:latest
    container_name: shaarli
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ~/data/shaarli-data/cache:/var/www/shaarli/cache
      - ~/data/shaarli-data/data:/var/www/shaarli/data
